name: dbtvault_greenplum_demo
profile: dbtvault_greenplum_demo
version: '5.1.0'
config-version: 2

vars:
  load_date: '1992-01-03'
  # tpch_size: 10 #1, 10, 100, 1000, 10000

models:
  dbtvault_greenplum_demo:
    raw_stage:
      tags:
        - 'raw'
      materialized: table
    stage:
      tags:
        - 'stage'
      enabled: true
      materialized: view
    raw_vault:
      tags:
        - 'raw_vault'
      materialized: incremental
      hubs:
        tags:
          - 'hub'
      links:
        tags:
          - 'link'
      sats:
        tags:
          - 'satellite'
      t_links:
        tags:
          - 't_link'

# path to compiled .sql files
target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

analysis-paths:
  - analysis
clean-targets:
  - target
data-paths:
  - data
macro-paths:
  - macros
source-paths:
  - models
test-paths:
  - tests
target-path: target    